services:
  - type: web
    name: giveaway-bot
    runtime: python
    buildCommand: ""
    startCommand: "python main.py"
    envVars:
      - key: DISCORD_TOKEN
        sync: false
      - key: GUILD_ID
        sync: false
